openapi: 3.0.0
info:
  title: RatGTEx REST API
  version: '3.0.0'
  description: This API provides data for the visualizations in the RatGTEx data portal. This version (v3) provides data for RatGTEx data release v3, which uses the rn7 (mRatBN7.2) genome assembly.
  contact:
    name: Daniel Munro
    x-role: responsible developer
    email: danbmunro@gmail.com
    url: https://danmun.ro
    x-id: https://danmun.ro
servers:
- url: https://ratgtex.org/api/v3
  description: RatGTEx data portal
tags:
- name: reference
  description: Information on tissues, genes, and variants
- name: expression
  description: Gene expression data
- name: eQTL
  description: Data on gene-variant associations
- name: sQTL
  description: Data on splice-variant associations
paths:
  /dyneqtl:
    get:
      tags:
      - eQTL
      description: Fetch information for one gene-variant pair in one tissue
      parameters:
      - name: geneId
        in: query
        description: Gene ID
        required: true
        schema:
          type: string
          example: Cd300lf
      - name: tissueSiteDetailId
        in: query
        description: Tissue ID
        required: true
        schema:
          type: string
          example: IL
      - name: variantId
        in: query
        description: Variant ID
        required: true
        schema:
          type: string
          example: chr10:104362850
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  alt:
                    type: string
                    example: A
                  data:
                    type: array
                    items:
                      type: number
                    example: [-1.11134883833383, -0.314562734207873, 0.556543703618366, 0.522265760640944]
                  geneId:
                    type: string
                    example: Cd300lf
                  genotypes:
                    type: array
                    items:
                      type: integer
                    example: [1, 0, 2, 1]
                  hetCount:
                    type: integer
                    example: 34
                  homoAltCount:
                    type: integer
                    example: 17
                  homoRefCount:
                    type: integer
                    example: 30
                  maf:
                    type: number
                    example: 0.41975308641975306
                  pValue:
                    type: number
                    example: 0.0000203971
                  pValueThreshold:
                    type: number
                    example: 0.00220875
                  ref:
                    type: string
                    example: G
                  tissueSiteDetailId:
                    type: string
                    example: IL
                  variantId:
                    type: string
                    example: chr10:104362850
  /eqtl:
    get:
      tags:
      - eQTL
      description: Fetch conditionally independent cis-eQTLs in any tissue for a gene
      parameters:
      - name: geneId
        in: query
        description: Gene ID
        required: true
        schema:
          type: string
          example: Cd300lf
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  eqtl:
                    type: array
                    items:
                      type: object
                      properties:
                        alt:
                          type: string
                          example: T
                        geneId:
                          type: string
                          example: Cd300lf
                        log2_aFC:
                          type: number
                          example: 0.401466
                        pval_beta:
                          type: number
                          example: 0.000715545
                        ref:
                          type: string
                          example: C
                        tissueSiteDetailId:
                          type: string
                          example: IL
                        variantId:
                          type: string
                          example: chr10:104378687
  /exon:
    get:
      tags:
      - reference
      description: Fetch a gene's exons
      parameters:
      - name: geneId
        in: query
        description: Gene ID
        required: true
        schema:
          type: string
          example: Cd300lf
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  exon:
                    type: array
                    items:
                      type: object
                      properties:
                        chromosome:
                          type: string
                          example: chr1
                        end:
                          type: integer
                          example: 103687425
                        exonId:
                          type: string
                          example: Cd300lf_1
                        exonNumber:
                          type: integer
                          example: 1
                        featureType:
                          type: string
                          example: exon
                        geneId:
                          type: string
                          example: Cd300lf
                        start:
                          type: integer
                          example: 103687126
                        strand:
                          type: string
                          enum: ['-', '+']
                          example: '-'
                        transcriptId:
                          type: string
                          example: Cd300lf
  /gene:
    get:
      tags:
      - reference
      description: Fetch metadata for one or more genes
      parameters:
      - name: geneId
        in: query
        description: One or more gene IDs
        required: true
        schema:
          type: array
          items:
            type: string
          example: [Cd300lf, Eno1]
        style: form
        explode: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  gene:
                    type: array
                    items:
                      type: object
                      properties:
                        chromosome:
                          type: string
                          example: chr1
                        description:
                          type: string
                          example: Cd300 molecule-like family member F
                        end:
                          type: integer
                          example: 103687425
                        statusInTissue:
                          type: array
                          items:
                            type: object
                            properties:
                              tissueSiteDetailId:
                                type: string
                                example: IL
                              expressed:
                                type: boolean
                                example: true
                              testedEqtl:
                                type: boolean
                                example: true
                              eqtl:
                                type: boolean
                                example: true
                              altSplice:
                                type: boolean
                                example: true
                              testedSqtl:
                                type: boolean
                                example: true
                              sqtl:
                                type: boolean
                                example: true
                        geneId:
                          type: string
                          example: Cd300lf
                        hasEqtl:
                          type: boolean
                          example: true
                        start:
                          type: string
                          example: 103670027
                        strand:
                          type: string
                          example: '-'
                        tss:
                          type: integer
                          example: 103687425
  /ld:
    get:
      tags:
      - reference
      description: Fetch LD scores between all cis-window variants for a gene
      parameters:
      - name: geneId
        in: query
        description: Gene ID
        required: true
        schema:
          type: string
          example: Cd300lf
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  ld:
                    type: array
                    items:
                      type: array
                      items: {}
                      example: [chr10:102827930, chr10:102868675, 0.6863]
  /medianGeneExpression:
    get:
      tags:
      - expression
      description: Fetch median expression (TPM) for one or more genes in one or more tissues
      parameters:
      - name: geneId
        in: query
        description: One or more gene IDs.
        required: true
        schema:
          type: array
          items:
            type: string
          example: [Polr3k, Rtel1, Eno1]
        style: form
        explode: false
      - name: tissueSiteDetailId
        in: query
        description: One or more tissue IDs. If omitted, all tissues are included.
        required: false
        schema:
          type: array
          items:
            type: string
          example: [IL, LHb, NAcc]
        style: form
        explode: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  clusters:
                    type: object
                    properties:
                      gene:
                        type: string
                        example: '((Polr3k:209.196,Rtel1:209.196):759.14,Eno1:968.336);'
                      tissue:
                        type: string
                        example: '((IL:34.6518,LHb:34.6518):191.47,NAcc:226.121);'
                  medianGeneExpression:
                    type: array
                    items:
                      type: object
                      properties:
                        geneId:
                          type: string
                          example: Rtel1
                        median:
                          type: number
                          example: 134.87
                        tissueSiteDetailId:
                          type: string
                          example: IL
  /singleTissueEqtl:
    get:
      tags:
      - eQTL
      description: Fetch all significant cis-variants in all tissues for a gene
      parameters:
      - name: geneId
        in: query
        description: Gene ID
        required: true
        schema:
          type: string
          example: Card19
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  singleTissueEqtl:
                    type: array
                    items:
                      type: object
                      properties:
                        chromosome:
                          type: string
                          example: chr1
                        geneId:
                          type: string
                          example: Card19
                        nes:
                          type: number
                          example: 1.19669
                        pValue:
                          type: number
                          example: 0.00121899
                        pos:
                          type: integer
                          example: 15221388
                        tissueSiteDetailId:
                          type: string
                          example: NAcc
                        variantId:
                          type: string
                          example: chr17:15221388
  /sqtl:
    get:
      tags:
      - sQTL
      description: Fetch conditionally independent cis-sQTLs in any tissue for a gene
      parameters:
      - name: geneId
        in: query
        description: Gene ID
        required: true
        schema:
          type: string
          example: Cd300lf
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  eqtl:
                    type: array
                    items:
                      type: object
                      properties:
                        alt:
                          type: string
                          example: T
                        geneId:
                          type: string
                          example: Cd300lf
                        phenotypeId:
                          type: string
                          example: chr10:103673824:103677398:clu_5465_-:Cd300lf
                        pval_beta:
                          type: number
                          example: 0.000715545
                        ref:
                          type: string
                          example: C
                        tissueSiteDetailId:
                          type: string
                          example: IL
                        variantId:
                          type: string
                          example: chr10:104378687
  /tissueInfo:
    get:
      tags:
      - reference
      description: Fetch metadata for all tissues
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  tissueInfo:
                    type: array
                    items:
                      type: object
                      properties:
                        colorHex:
                          type: string
                          example: 377eb8
                        colorRgb:
                          type: string
                          example: '55,126,184'
                        dataset:
                          type: string
                          example: ratgtex_v3_round10_5
                        datasetId:
                          type: string
                          example: ratgtex_v3
                        eGeneCount:
                          type: integer
                          example: 3949
                        expressedGeneCount:
                          type: integer
                          example: 16563
                        hasEgenes:
                          type: boolean
                          example: true
                        rnaSeqAndGenotypeSampleCount:
                          type: integer
                          example: 81
                        rnaSeqSampleCount:
                          type: integer
                          example: 81
                        tissueSite:
                          type: string
                          example: Brain
                        tissueSiteDetail:
                          type: string
                          example: Infralimbic cortex
                        tissueSiteDetailAbbr:
                          type: string
                          example: IL
                        tissueSiteDetailId:
                          type: string
                          example: IL
  /topExpressedGene:
    get:
      tags:
      - expression
      description: Fetch 50 genes with highest median expression in a tissue
      parameters:
      - name: filterMtGene
        in: query
        description: Whether mitochondrial genes should be omitted from the top gene list
        required: false
        schema:
          type: boolean
          example: true
      - name: tissueSiteDetailId
        in: query
        description: Tissue ID
        required: true
        schema:
          type: string
          example: IL
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  topExpressedGene:
                    type: array
                    items:
                      type: object
                      properties:
                        datasetId:
                          type: string
                          example: ratgtex_v3
                        geneId:
                          type: string
                          example: AY172581.9
                        median:
                          type: number
                          example: 6068.27
                        tissueSiteDetailId:
                          type: string
                          example: IL
                        unit:
                          type: string
                          enum: [TPM]
                          example: TPM
  /variant:
    get:
      tags:
      - reference
      description: Fetch information for one or more variants
      parameters:
      - name: variantId
        in: query
        description: Variant ID
        required: true
        schema:
          type: array
          items:
            type: string
          example: [chr1:1675342, chr5:154001168]
        style: form
        explode: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  variant:
                    type: array
                    items:
                      type: object
                      properties:
                        alt:
                          type: string
                          example: A
                        chromosome:
                          type: string
                          example: chr1
                        pos:
                          type: integer
                          example: 1675342
                        ref:
                          type: string
                          example: G
                        variantId:
                          type: string
                          example: chr1:1675342
